# Generated by Django 5.0.6 on 2024-06-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ferramax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('CodigoProducto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('IdInventario', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CodigoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ferramax.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('IdDescripcion', models.AutoField(primary_key=True, serialize=False)),
                ('Detalles', models.TextField()),
                ('Categoria', models.CharField(max_length=255)),
                ('CodigoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ferramax.producto')),
            ],
        ),
    ]
